/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JFrameQuanLyKyTucXa;

import Connector.KetNoiSQL;
import dao.GiaHanDAO;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ThongTinGiaHan;
import model.ThongTinSinhVien;
import textfield.SearchOptinEvent;
import textfield.SearchOption;

/**
 *
 * @author huuzinhh
 */
public class GiaHan extends javax.swing.JPanel {

    private List<ThongTinGiaHan> list;
    private DefaultTableModel Model;
    private DefaultTableModel TableView;
    private int count = -1;
    private String maSV;

    public GiaHan() {
        initComponents();
        Model = (DefaultTableModel) tablePhong.getModel();
        showTable();
        tablePhong.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tablePhong.getTableHeader().setOpaque(false);
        tablePhong.getTableHeader().setBackground(new Color(19, 90, 118));
        tablePhong.getTableHeader().setForeground(new Color(225, 225, 225));
        AddSearch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuanLyThongTinGiaHanHD = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ScrollPaneSV = new javax.swing.JScrollPane();
        tablePhong = new javax.swing.JTable();
        view = new javax.swing.JLabel();
        txtSearch = new textfield.TextFieldSearchOption();
        ViewPhong = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JLabel();
        txtNgayKTHD = new javax.swing.JLabel();
        jButtonDY = new javax.swing.JButton();
        jButtonTC = new javax.swing.JButton();
        jLabelGiaHan = new javax.swing.JLabel();

        QuanLyThongTinGiaHanHD.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(237, 50, 55));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý thông tin gia hạn hợp đồng");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(19, 90, 118)));

        ScrollPaneSV.setBackground(new java.awt.Color(255, 255, 255));
        ScrollPaneSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScrollPaneSVMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ScrollPaneSVMouseExited(evt);
            }
        });

        tablePhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablePhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sinh viên", "Ngày kết thúc hợp đồng", "Thời gian gia hạn", "Trạng thái"
            }
        ));
        tablePhong.setFocusable(false);
        tablePhong.setGridColor(new java.awt.Color(255, 255, 255));
        tablePhong.setRowHeight(25);
        tablePhong.setSelectionBackground(new java.awt.Color(19, 90, 118));
        tablePhong.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tablePhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePhongMouseClicked(evt);
            }
        });
        ScrollPaneSV.setViewportView(tablePhong);

        view.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eye_table.png"))); // NOI18N
        view.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMouseClicked(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout QuanLyThongTinGiaHanHDLayout = new javax.swing.GroupLayout(QuanLyThongTinGiaHanHD);
        QuanLyThongTinGiaHanHD.setLayout(QuanLyThongTinGiaHanHDLayout);
        QuanLyThongTinGiaHanHDLayout.setHorizontalGroup(
            QuanLyThongTinGiaHanHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(QuanLyThongTinGiaHanHDLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(QuanLyThongTinGiaHanHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyThongTinGiaHanHDLayout.createSequentialGroup()
                        .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(QuanLyThongTinGiaHanHDLayout.createSequentialGroup()
                        .addComponent(ScrollPaneSV, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(68, Short.MAX_VALUE))))
        );
        QuanLyThongTinGiaHanHDLayout.setVerticalGroup(
            QuanLyThongTinGiaHanHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyThongTinGiaHanHDLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QuanLyThongTinGiaHanHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPaneSV, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 66, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(19, 90, 118));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Hệ thống quản lý ký túc xá sinh viên");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(237, 50, 55));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Thông tin chi tiết ");

        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back_main.png"))); // NOI18N
        jLabel55.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel55MouseClicked(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(19, 90, 118));
        jLabel23.setText("Ngày hết hợp đồng:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(19, 90, 118));
        jLabel25.setText("Gia hạn:");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(19, 90, 118));
        jLabel26.setText("Mã sinh viên :");

        txtMaSV.setBackground(new java.awt.Color(255, 255, 255));
        txtMaSV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMaSV.setForeground(new java.awt.Color(19, 90, 118));

        txtNgayKTHD.setBackground(new java.awt.Color(255, 255, 255));
        txtNgayKTHD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNgayKTHD.setForeground(new java.awt.Color(19, 90, 118));

        jButtonDY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDY.setForeground(new java.awt.Color(237, 50, 55));
        jButtonDY.setText("Đồng ý");
        jButtonDY.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(19, 90, 118)));
        jButtonDY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDYActionPerformed(evt);
            }
        });

        jButtonTC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTC.setForeground(new java.awt.Color(237, 50, 55));
        jButtonTC.setText("Từ chối");
        jButtonTC.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(19, 90, 118)));
        jButtonTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTCActionPerformed(evt);
            }
        });

        jLabelGiaHan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelGiaHan.setForeground(new java.awt.Color(19, 90, 118));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 157, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonDY, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(jButtonTC, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNgayKTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGiaHan, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNgayKTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGiaHan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDY, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ViewPhongLayout = new javax.swing.GroupLayout(ViewPhong);
        ViewPhong.setLayout(ViewPhongLayout);
        ViewPhongLayout.setHorizontalGroup(
            ViewPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ViewPhongLayout.setVerticalGroup(
            ViewPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1068, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(QuanLyThongTinGiaHanHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ViewPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(QuanLyThongTinGiaHanHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ViewPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablePhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePhongMouseClicked
        // TODO add your handling code here:
        count = tablePhong.getSelectedRow();
    }//GEN-LAST:event_tablePhongMouseClicked

    private void ScrollPaneSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScrollPaneSVMouseClicked

    }//GEN-LAST:event_ScrollPaneSVMouseClicked

    private void ScrollPaneSVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScrollPaneSVMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ScrollPaneSVMouseExited

    private void viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseClicked
        // TODO add your handling code here:
        if (count == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn phòng để xem!");
        } else {
            LayThongTinUp(count);
            QuanLyThongTinGiaHanHD.setVisible(false);
            ViewPhong.setVisible(true);
            //            LayMaPhong(count);
            //            showTableView(maSV);
        }

    }//GEN-LAST:event_viewMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        if (txtSearch.isSelected()) {
            int option = txtSearch.getSelectedIndex();
            String textsearch = txtSearch.getText().trim();
            if (option == 0) {
                showTable("maSV", textsearch);
            } else if (option == 1) {
                showTable("ngayKTHD", textsearch);
            } else if (option == 2) {
                showTable("thoiGianGiaHan", textsearch);
            } else if (option == 3) {
                showTable("trangThai", textsearch);
            }
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jLabel55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel55MouseClicked
        // TODO add your handling code here:
        QuanLyThongTinGiaHanHD.setVisible(true);
        ViewPhong.setVisible(false);
    }//GEN-LAST:event_jLabel55MouseClicked

    private void jButtonDYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDYActionPerformed
        // TODO add your handling code here:
        ThongTinGiaHan gh = list.get(count);
        maSV = gh.getMaSV();
        updateHD_NKT(maSV);
        updateGH_TrangThai2(txtMaSV.getText().trim());

    }//GEN-LAST:event_jButtonDYActionPerformed

    private void jButtonTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTCActionPerformed
        updateGH_TrangThai0(txtMaSV.getText().trim());
    }//GEN-LAST:event_jButtonTCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel QuanLyThongTinGiaHanHD;
    private javax.swing.JScrollPane ScrollPaneSV;
    private javax.swing.JPanel ViewPhong;
    private javax.swing.JButton jButtonDY;
    private javax.swing.JButton jButtonTC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabelGiaHan;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable tablePhong;
    private javax.swing.JLabel txtMaSV;
    private javax.swing.JLabel txtNgayKTHD;
    private textfield.TextFieldSearchOption txtSearch;
    private javax.swing.JLabel view;
    // End of variables declaration//GEN-END:variables

    void showTable() {
        list = new GiaHanDAO().getAllThongTinGiaHan();
        Model.setRowCount(0);
        String trangthai = null;
        for (ThongTinGiaHan gh : list) {
            int k = gh.getTrangThai();
            if (k == 0) {
                trangthai = "Từ chối";
            } else if (k == 1) {
                trangthai = "Đang chờ duyệt";
            } else if (k == 2) {
                trangthai = "Đồng ý";
            }

            Model.addRow(new Object[]{
                gh.getMaSV(), gh.getNgayHDKT(), gh.getThoiGianGiaHan(), trangthai
            });
        }
        count = -1;

    }

    private void showTable(String where, String text) {
        list = new GiaHanDAO().getAllThongTinChuyenPhongSearch(where, text);
        Model.setRowCount(0);
        String trangthai = null;
        for (ThongTinGiaHan gh : list) {
            int k = gh.getTrangThai();
            if (k == 0) {
                trangthai = "Từ chối";
            } else if (k == 1) {
                trangthai = "Đang chờ duyệt";
            } else if (k == 2) {
                trangthai = "Đồng ý";
            }
            Model.addRow(new Object[]{
                gh.getMaSV(), gh.getNgayHDKT(), gh.getThoiGianGiaHan(), trangthai
            });
        }
    }

    void LayThongTinUp(int count) {
        ThongTinGiaHan gh = list.get(count);
        SimpleDateFormat sp = new SimpleDateFormat("dd-MM-yyyy");
        txtMaSV.setText(gh.getMaSV());
        txtNgayKTHD.setText(sp.format(gh.getNgayHDKT()));
        jLabelGiaHan.setText(Integer.toString(gh.getThoiGianGiaHan()));

    }

    void AddSearch() {
        txtSearch.addEventOptionSelected(new SearchOptinEvent() {
            @Override
            public void optionSelected(SearchOption option, int index) {
                txtSearch.setHint("Tìm kiếm " + option.getName() + "....");
            }
        });
        txtSearch.addOption(new SearchOption("mã sinh viên", new ImageIcon(getClass().getResource("/img/people.png"))));
        txtSearch.addOption(new SearchOption("ngày kết thúc hợp đồng", new ImageIcon(getClass().getResource("/img/home.png"))));
        txtSearch.addOption(new SearchOption("thời gian gia hạn", new ImageIcon(getClass().getResource("/img/money.png"))));
        txtSearch.addOption(new SearchOption("trạng thái", new ImageIcon(getClass().getResource("/img/pencil.png"))));

    }

    private void updateGH_TrangThai2(String maSv) {
        Connection conn = KetNoiSQL.getConnection();
        String sql = "update GiaHan set trangThai='2' where maSV='" + maSv + "'";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.executeUpdate();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi chuyen khong thanh cong");
        }
    }

    private void updateGH_TrangThai0(String maSv) {
        Connection conn = KetNoiSQL.getConnection();
        String sql = "update GiaHan set trangThai='0' where maSV='" + maSv + "'";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.executeUpdate();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi chuyen khong thanh cong");
        }
    }

    private void updateHD_NKT(String msv) {
        ThongTinGiaHan gh = new GiaHanDAO().getAllThongTinGiaHanTheoMaSV(msv);

        Date NKT = gh.getNgayHDKT();
        
        SimpleDateFormat sp = new SimpleDateFormat("yyyy-MM-dd");
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(NKT);
        calendar.add(Calendar.MONTH, gh.getThoiGianGiaHan());
       
        
        
        Date datesv;
        String datestr = "";
        Calendar cld = Calendar.getInstance();
        Date date1 = gh.getNgayHDKT();

        cld.setTime(date1);
        cld.add(Calendar.MONTH, gh.getThoiGianGiaHan());
        datesv = cld.getTime();
        datestr = sp.format(datesv);

        Connection conn = KetNoiSQL.getConnection();
        String sql = "update hopdongktx set ngayHDKT='" + datestr + "' where maSV='" + msv + "'";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Gia hạn thành công");
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gia hạn không thành công");
        }
    }

}
