/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrameQuanLyKyTucXa;

import Connector.KetNoiSQL;
import dao.HopDongKTXDAO;
import dao.SinhVienDAO;
import dao.ThongTinDichVuDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ThongTinSinhVien;

/**
 *
 * @author PhanTien
 */
public class Main extends javax.swing.JFrame {

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private List<ThongTinSinhVien> listsinhvien;
    private DefaultTableModel Model;
    private int count = 0;
    private SinhVienDAO sinhviendao;
    String tenDangNhap;
    private String email;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        UpdateSinhVien();
    }

    void setnameuser(String email) {
        this.email = email;
        Connection conn = KetNoiSQL.getConnection();
        String sql = "select * from nhanvien where email='" + email + "'";
        try {
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            ResultSet rs = preparedStatement.executeQuery();
            while (rs.next()) {
                txtnameuser.setText(rs.getString("tenNV"));
            }
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnameuser = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanelTrangChu = new JFrameQuanLyKyTucXa.TrangChu();
        jPanelQuanLySV = new JFrameQuanLyKyTucXa.QuanLySV();
        jPanelQuanLyDK = new JFrameQuanLyKyTucXa.QuanLySinhVienDK();
        jPanelQuanLyPhong = new JFrameQuanLyKyTucXa.QuanLyPhong();
        jPanelCaiDatTaiKhoan = new JFrameQuanLyKyTucXa.CaiDatTaiKhoan();
        jPanelQuanLyNhanVien = new JFrameQuanLyKyTucXa.QuanLyNhanVien();
        jPanelThongTinTaiKhoan = new JFrameQuanLyKyTucXa.ThongTinTK_NV();
        thongbao1 = new JFrameQuanLyKyTucXa.Thongbao();
        jPanelKhoanPhi = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        quanLyDienNuoc1 = new JFrameQuanLyKyTucXa.QuanLyDienNuoc();
        jpanelQuanLyTienPhong1 = new JFrameQuanLyKyTucXa.JpanelQuanLyTienPhong();
        jPanelHopDongKTX = new JFrameQuanLyKyTucXa.HopDongKTX();
        jPanelPhanQuyen = new JFrameQuanLyKyTucXa.PhanQuyenNguoiDung();
        jPanelThongKe = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        thongKeSinhVien1 = new JFrameQuanLyKyTucXa.ThongKeSinhVien();
        thongKePhong1 = new JFrameQuanLyKyTucXa.ThongKePhong();
        thongKeNhanVien1 = new JFrameQuanLyKyTucXa.ThongKeNhanVien();
        thongKeDichVuPhong1 = new JFrameQuanLyKyTucXa.ThongKeDichVuPhong();
        jPanelChuyenPhong = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        giaHan1 = new JFrameQuanLyKyTucXa.GiaHan();
        jpanelChuyenPhong1 = new JFrameQuanLyKyTucXa.JpanelChuyenPhong();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(-50, 20));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(19, 90, 118));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo Học Viện Công Nghệ Bưu Chính Viễn Thông - PTIT(Simple).png"))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UserName:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menu:");

        txtnameuser.setForeground(new java.awt.Color(255, 255, 255));
        txtnameuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnameuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_name.png"))); // NOI18N
        txtnameuser.setText("Phan Van Tien");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil.png"))); // NOI18N
        jLabel5.setText("Phân quyền người dùng");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/people.png"))); // NOI18N
        jLabel6.setText("Quản lý sinh viên");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bank.png"))); // NOI18N
        jLabel7.setText("Quản lý phòng");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bag.png"))); // NOI18N
        jLabel8.setText("Hợp đồng KTX");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/money_bag.png"))); // NOI18N
        jLabel11.setText("Các khoản phí");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/thongke.png"))); // NOI18N
        jLabel12.setText("Thống kê");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jLabel13.setText("Thông tin tài khoản");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jLabel15.setText("Trang chủ");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/out.png"))); // NOI18N
        jLabel16.setText("LogOut");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/setting.png"))); // NOI18N
        jLabel14.setText("Cài lại mật khẩu");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/people.png"))); // NOI18N
        jLabel18.setText("Quản lý nhân viên");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/setting.png"))); // NOI18N
        jLabel17.setText("Thông báo");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bag.png"))); // NOI18N
        jLabel19.setText("Quản lý chuyển,gia hạn phòng");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnameuser, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnameuser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelmenu.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_ptit.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1362, 567));
        jPanel5.setLayout(new java.awt.CardLayout());
        jPanel5.add(jPanelTrangChu, "card3");
        jPanel5.add(jPanelQuanLySV, "card4");
        jPanel5.add(jPanelQuanLyDK, "card4");
        jPanel5.add(jPanelQuanLyPhong, "card5");
        jPanel5.add(jPanelCaiDatTaiKhoan, "card7");
        jPanel5.add(jPanelQuanLyNhanVien, "card13");
        jPanel5.add(jPanelThongTinTaiKhoan, "card12");
        jPanel5.add(thongbao1, "card12");

        jPanelKhoanPhi.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setForeground(new java.awt.Color(19, 90, 118));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTabbedPane1.addTab("QUẢN LÝ ĐIỆN NƯỚC", quanLyDienNuoc1);
        jTabbedPane1.addTab("QUẢN LÝ TIỀN PHÒNG", jpanelQuanLyTienPhong1);

        javax.swing.GroupLayout jPanelKhoanPhiLayout = new javax.swing.GroupLayout(jPanelKhoanPhi);
        jPanelKhoanPhi.setLayout(jPanelKhoanPhiLayout);
        jPanelKhoanPhiLayout.setHorizontalGroup(
            jPanelKhoanPhiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKhoanPhiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1092, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanelKhoanPhiLayout.setVerticalGroup(
            jPanelKhoanPhiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKhoanPhiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.add(jPanelKhoanPhi, "card13");
        jPanel5.add(jPanelHopDongKTX, "card13");
        jPanel5.add(jPanelPhanQuyen, "card14");

        jPanelThongKe.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jTabbedPane2.setForeground(new java.awt.Color(19, 90, 118));
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTabbedPane2.addTab("THỐNG KÊ SINH VIÊN", thongKeSinhVien1);
        jTabbedPane2.addTab("THỐNG KÊ PHÒNG", thongKePhong1);
        jTabbedPane2.addTab("THỐNG KÊ NHÂN VIÊN", thongKeNhanVien1);
        jTabbedPane2.addTab("THỐNG KÊ HÓA ĐƠN", thongKeDichVuPhong1);

        javax.swing.GroupLayout jPanelThongKeLayout = new javax.swing.GroupLayout(jPanelThongKe);
        jPanelThongKe.setLayout(jPanelThongKeLayout);
        jPanelThongKeLayout.setHorizontalGroup(
            jPanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1092, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanelThongKeLayout.setVerticalGroup(
            jPanelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.add(jPanelThongKe, "card13");

        jPanelChuyenPhong.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane3.setForeground(new java.awt.Color(19, 90, 118));
        jTabbedPane3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTabbedPane3.addTab("QUẢN LÝ GIA HẠN PHÒNG", giaHan1);
        jTabbedPane3.addTab("QUẢN LÝ CHUYỂN PHÒNG", jpanelChuyenPhong1);

        jLabel4.setBackground(new java.awt.Color(19, 90, 112));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(19, 90, 118));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" TRANG THÔNG TIN SINH VIÊN Ở KÝ TÚC XÁ CỦA HỌC VIỆN ");

        javax.swing.GroupLayout jPanelChuyenPhongLayout = new javax.swing.GroupLayout(jPanelChuyenPhong);
        jPanelChuyenPhong.setLayout(jPanelChuyenPhongLayout);
        jPanelChuyenPhongLayout.setHorizontalGroup(
            jPanelChuyenPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1113, Short.MAX_VALUE)
        );
        jPanelChuyenPhongLayout.setVerticalGroup(
            jPanelChuyenPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChuyenPhongLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
        );

        jPanel5.add(jPanelChuyenPhong, "card14");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1113, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        int test = JOptionPane.showConfirmDialog(null, "Bạn chắc có muốn đăng xuất hay không !", "Thông báo đăng nhập", JOptionPane.YES_NO_OPTION);
        if (test == JOptionPane.YES_OPTION) {
            dispose();
            Login login = new Login();
            login.show();
        } else if (test == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Bạn đã hủy đăng xuất");
        }

    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        jPanelTrangChu.setVisible(true);
        jPanelQuanLySV.setVisible(false);
        jPanelQuanLyDK.setVisible(false);
        jPanelQuanLyPhong.setVisible(false);
        jPanelThongKe.setVisible(false);
        jPanelThongTinTaiKhoan.setVisible(false);
        jPanelHopDongKTX.setVisible(false);
        //jPanelPhanQuyen.setVisible(false);
        jPanelKhoanPhi.setVisible(false);
        jPanelCaiDatTaiKhoan.setVisible(false);
        jPanelQuanLyNhanVien.setVisible(false);
        thongbao1.setVisible(false);
        jPanelPhanQuyen.setVisible(false);
        jPanelChuyenPhong.setVisible(false);

        setnameuser(email);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        jPanelTrangChu.setVisible(false);
        jPanelQuanLySV.setVisible(true);
        jPanelQuanLyDK.setVisible(false);
        jPanelThongKe.setVisible(false);
        jPanelQuanLyPhong.setVisible(false);
        jPanelThongTinTaiKhoan.setVisible(false);
        jPanelKhoanPhi.setVisible(false);
        jPanelHopDongKTX.setVisible(false);
        //jPanelPhanQuyen.setVisible(false);
        jPanelCaiDatTaiKhoan.setVisible(false);
        jPanelQuanLyNhanVien.setVisible(false);
        thongbao1.setVisible(false);
        jPanelPhanQuyen.setVisible(false);
        jPanelChuyenPhong.setVisible(false);

        setnameuser(email);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        jPanelTrangChu.setVisible(false);
        jPanelQuanLySV.setVisible(false);
        jPanelQuanLyDK.setVisible(false);
        jPanelQuanLyPhong.setVisible(false);
        jPanelThongKe.setVisible(false);
        jPanelThongTinTaiKhoan.setVisible(false);
        jPanelKhoanPhi.setVisible(false);
        jPanelQuanLyNhanVien.setVisible(false);
        jPanelHopDongKTX.setVisible(true);
        //jPanelPhanQuyen.setVisible(false);
        jPanelCaiDatTaiKhoan.setVisible(false);
        thongbao1.setVisible(false);
        jPanelPhanQuyen.setVisible(false);
        jPanelChuyenPhong.setVisible(false);
        this.jPanelHopDongKTX.showTable();
        setnameuser(email);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        jPanelTrangChu.setVisible(false);
        jPanelQuanLySV.setVisible(false);
        jPanelQuanLyDK.setVisible(false);
        jPanelThongKe.setVisible(false);
        jPanelQuanLyPhong.setVisible(true);
        jPanelThongTinTaiKhoan.setVisible(false);
        //jPanelPhanQuyen.setVisible(false);
        jPanelCaiDatTaiKhoan.setVisible(false);
        jPanelQuanLyNhanVien.setVisible(false);
        jPanelKhoanPhi.setVisible(false);
        thongbao1.setVisible(false);
        jPanelQuanLyPhong.showTable();
        jPanelHopDongKTX.setVisible(false);
        jPanelPhanQuyen.setVisible(false);
        jPanelChuyenPhong.setVisible(false);
        jPanelQuanLyPhong.showTable();

        setnameuser(email);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        jPanelTrangChu.setVisible(false);
        jPanelQuanLySV.setVisible(false);
        jPanelQuanLyDK.setVisible(false);
        jPanelQuanLyPhong.setVisible(false);
        jPanelThongKe.setVisible(false);
        jPanelThongTinTaiKhoan.setVisible(true);
        jPanelQuanLyNhanVien.setVisible(false);
        // jPanelPhanQuyen.setVisible(false);
        jPanelCaiDatTaiKhoan.setVisible(false);
        jPanelKhoanPhi.setVisible(false);
        thongbao1.setVisible(false);
        jPanelHopDongKTX.setVisible(false);
        jPanelPhanQuyen.setVisible(false);
        jPanelChuyenPhong.setVisible(false);

        setnameuser(email);
        this.jPanelThongTinTaiKhoan.showViewTaiKhoan(email);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        jPanelTrangChu.setVisible(false);
        jPanelQuanLySV.setVisible(false);
        jPanelQuanLyNhanVien.setVisible(false);
        jPanelQuanLyDK.setVisible(false);
        jPanelQuanLyPhong.setVisible(false);
        jPanelThongTinTaiKhoan.setVisible(false);
        //jPanelPhanQuyen.setVisible(false);
        jPanelThongKe.setVisible(false);
        jPanelHopDongKTX.setVisible(false);
        jPanelCaiDatTaiKhoan.setVisible(true);
        jPanelKhoanPhi.setVisible(false);
        thongbao1.setVisible(false);
        jPanelPhanQuyen.setVisible(false);
        jPanelChuyenPhong.setVisible(false);

        setnameuser(email);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:jPanelTrangChu.setVisible(false);
        jPanelQuanLySV.setVisible(false);
        jPanelTrangChu.setVisible(false);
        jPanelQuanLyDK.setVisible(false);
        jPanelQuanLyPhong.setVisible(false);
        jPanelThongTinTaiKhoan.setVisible(false);
        jPanelQuanLyNhanVien.setVisible(false);
        jPanelCaiDatTaiKhoan.setVisible(false);
        jPanelPhanQuyen.setVisible(true);
        jPanelHopDongKTX.setVisible(false);
        jPanelKhoanPhi.setVisible(false);
        jPanelThongKe.setVisible(false);
        thongbao1.setVisible(false);
        jPanelChuyenPhong.setVisible(false);

        //this.jPanelPhanQuyen.AddComboBox();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        jPanelQuanLySV.setVisible(false);
        jPanelTrangChu.setVisible(false);
        jPanelQuanLyDK.setVisible(false);
        jPanelQuanLyPhong.setVisible(false);
        jPanelThongTinTaiKhoan.setVisible(false);
        jPanelQuanLyNhanVien.setVisible(false);
        jPanelHopDongKTX.setVisible(false);
        jPanelCaiDatTaiKhoan.setVisible(false);
        //jPanelPhanQuyen.setVisible(false);
        jPanelKhoanPhi.setVisible(true);
        jPanelThongKe.setVisible(false);
        thongbao1.setVisible(false);
        jPanelPhanQuyen.setVisible(false);
        jPanelChuyenPhong.setVisible(false);


    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        jPanelQuanLySV.setVisible(false);
        jPanelTrangChu.setVisible(false);
        jPanelQuanLyDK.setVisible(false);
        jPanelQuanLyPhong.setVisible(false);
        jPanelThongTinTaiKhoan.setVisible(false);
        jPanelQuanLyNhanVien.setVisible(false);
        jPanelCaiDatTaiKhoan.setVisible(false);
        //jPanelPhanQuyen.setVisible(false);
        jPanelKhoanPhi.setVisible(false);
        jPanelHopDongKTX.setVisible(false);
        jPanelThongKe.setVisible(true);
        thongbao1.setVisible(false);
        jPanelPhanQuyen.setVisible(false);
        jPanelChuyenPhong.setVisible(false);
        try {
            thongKeSinhVien1.setup();
            thongKeSinhVien1.setThongKe();
            thongKeNhanVien1.setup();
            thongKeNhanVien1.setThongKe();
            thongKePhong1.setup();
            thongKePhong1.setThongKe();
            thongKeDichVuPhong1.setBieuDoDichVu();
            thongKeDichVuPhong1.showDichVu();
            thongKeDichVuPhong1.LocKetQuaAll();
        } catch (Exception e) {
        }


    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:

        jPanelTrangChu.setVisible(false);
        jPanelQuanLySV.setVisible(false);
        jPanelQuanLyDK.setVisible(false);
        jPanelQuanLyPhong.setVisible(false);
        jPanelThongKe.setVisible(false);
        jPanelThongTinTaiKhoan.setVisible(false);
        //jPanelPhanQuyen.setVisible(false);
        jPanelKhoanPhi.setVisible(false);
        jPanelHopDongKTX.setVisible(false);
        jPanelCaiDatTaiKhoan.setVisible(false);

        jPanelQuanLyNhanVien.setVisible(true);
        thongbao1.setVisible(false);
        jPanelPhanQuyen.setVisible(false);
        jPanelChuyenPhong.setVisible(false);

        setnameuser(email);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        jPanelTrangChu.setVisible(false);
        jPanelQuanLySV.setVisible(false);
        jPanelQuanLyDK.setVisible(false);
        jPanelQuanLyPhong.setVisible(false);
        jPanelThongKe.setVisible(false);
        jPanelThongTinTaiKhoan.setVisible(false);
        jPanelHopDongKTX.setVisible(false);
        //jPanelPhanQuyen.setVisible(false);
        jPanelKhoanPhi.setVisible(false);
        thongbao1.setVisible(true);
        jPanelCaiDatTaiKhoan.setVisible(false);

        jPanelQuanLyNhanVien.setVisible(false);
        jPanelPhanQuyen.setVisible(false);
        jPanelChuyenPhong.setVisible(false);

        setnameuser(email);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        jPanelTrangChu.setVisible(false);
        jPanelQuanLySV.setVisible(false);
        jPanelQuanLyDK.setVisible(false);
        jPanelQuanLyPhong.setVisible(false);
        jPanelThongKe.setVisible(false);
        jPanelThongTinTaiKhoan.setVisible(false);
        jPanelHopDongKTX.setVisible(false);
        //jPanelPhanQuyen.setVisible(false);
        jPanelKhoanPhi.setVisible(false);

        thongbao1.setVisible(false);
        jPanelCaiDatTaiKhoan.setVisible(false);
        jPanelQuanLyNhanVien.setVisible(false);
        jPanelPhanQuyen.setVisible(false);
        jPanelChuyenPhong.setVisible(true);

        setnameuser(email);
    }//GEN-LAST:event_jLabel19MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JFrameQuanLyKyTucXa.GiaHan giaHan1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private JFrameQuanLyKyTucXa.CaiDatTaiKhoan jPanelCaiDatTaiKhoan;
    private javax.swing.JPanel jPanelChuyenPhong;
    private JFrameQuanLyKyTucXa.HopDongKTX jPanelHopDongKTX;
    private javax.swing.JPanel jPanelKhoanPhi;
    private JFrameQuanLyKyTucXa.PhanQuyenNguoiDung jPanelPhanQuyen;
    private JFrameQuanLyKyTucXa.QuanLySinhVienDK jPanelQuanLyDK;
    private JFrameQuanLyKyTucXa.QuanLyNhanVien jPanelQuanLyNhanVien;
    private JFrameQuanLyKyTucXa.QuanLyPhong jPanelQuanLyPhong;
    private JFrameQuanLyKyTucXa.QuanLySV jPanelQuanLySV;
    private javax.swing.JPanel jPanelThongKe;
    private JFrameQuanLyKyTucXa.ThongTinTK_NV jPanelThongTinTaiKhoan;
    private JFrameQuanLyKyTucXa.TrangChu jPanelTrangChu;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private JFrameQuanLyKyTucXa.JpanelChuyenPhong jpanelChuyenPhong1;
    private JFrameQuanLyKyTucXa.JpanelQuanLyTienPhong jpanelQuanLyTienPhong1;
    private JFrameQuanLyKyTucXa.QuanLyDienNuoc quanLyDienNuoc1;
    private JFrameQuanLyKyTucXa.ThongKeDichVuPhong thongKeDichVuPhong1;
    private JFrameQuanLyKyTucXa.ThongKeNhanVien thongKeNhanVien1;
    private JFrameQuanLyKyTucXa.ThongKePhong thongKePhong1;
    private JFrameQuanLyKyTucXa.ThongKeSinhVien thongKeSinhVien1;
    private JFrameQuanLyKyTucXa.Thongbao thongbao1;
    private javax.swing.JLabel txtnameuser;
    // End of variables declaration//GEN-END:variables

    public void UpdateSinhVien() {
        List<ThongTinSinhVien> listsv = new SinhVienDAO().getAllThongTinSVTrangThai(2);
        for (ThongTinSinhVien sv : listsv) {
            LocalDate datelocal = LocalDate.now();
            SimpleDateFormat formatter1 = new SimpleDateFormat("yyyy-MM-dd");
            String strdatenow = String.valueOf(datelocal);
            Date datenow = null;
            try {
                datenow = formatter1.parse(strdatenow);
            } catch (Exception e) {
            }
            Date ngayHetHD = new HopDongKTXDAO().layNgayHDKTTuHDKTX(sv.getMaSV());
            if (ngayHetHD.compareTo(datenow) <= 0) {
                try {
                    Connection conn = KetNoiSQL.getConnection();
                    String sql = "update SinhVien set trangThai=? where maSV='" + sv.getMaSV() + "'";
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setInt(1, 3);
                    ps.executeUpdate();
                    ps.close();
                    conn.close();
                } catch (SQLException ex) {
                }
            }

        }
    }
}
