/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JFrameQuanLyKyTucXa;

import Connector.KetNoiSQL;
import dao.PhongDAO;
import dao.SinhVienDAO;
import dao.SinhVienDangKyDAO;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ThongTinPhong;
import model.ThongTinSinhVienDangKy;

/**
 *
 * @author PhanTien
 */
public class QuanLySinhVienDK extends javax.swing.JPanel {

    /**
     * Creates new form QuanLySinhVienDK
     */
    private List<ThongTinSinhVienDangKy> listsinhvien;
    private DefaultTableModel Model;
    private int count = -1;
    private String maSV, maphongg;
    private SinhVienDangKyDAO sinhviendao;
    private String selectedQueQuan, selectedMaPhong;
    private String tendangnhap;
    private String gioitinh, loaiphong;
    private String email, sdt, cccd;
    private Date datecr = new Date();

    public QuanLySinhVienDK() {
        initComponents();
        Model = (DefaultTableModel) tableSV.getModel();
        showTable();
        tableSV.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tableSV.getTableHeader().setOpaque(false);
        tableSV.getTableHeader().setBackground(new Color(19, 90, 118));
        tableSV.getTableHeader().setForeground(new Color(225, 225, 225));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        QuanLyThongTinSV = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ScrollPaneSV = new javax.swing.JScrollPane();
        tableSV = new javax.swing.JTable();
        addSV = new javax.swing.JLabel();
        deleteSV = new javax.swing.JLabel();
        UpdateSinhVien = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtUpEmail = new javax.swing.JTextField();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtUpTenSV = new javax.swing.JTextField();
        txtUpMaPhongSV = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtUpMaSoSV = new javax.swing.JTextField();
        txtUpMaLopSV = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtUpCCCD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnUpdateSV = new javax.swing.JButton();
        txtUpNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtUpSoDienThoaiSV = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtUpQueQuanSV = new javax.swing.JComboBox<>();

        setLayout(new java.awt.CardLayout());

        QuanLyThongTinSV.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(19, 90, 118));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý thông tin sinh viên đăng ký");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(19, 90, 118)));

        ScrollPaneSV.setBackground(new java.awt.Color(255, 255, 255));
        ScrollPaneSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScrollPaneSVMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ScrollPaneSVMouseExited(evt);
            }
        });

        tableSV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sinh viên", "Tên sinh viên", "CCCD", "Giới tính", "Ngày sinh", "Mã lớp ", "Số điện thoại", "Tỉnh Thành"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableSV.setFocusable(false);
        tableSV.setGridColor(new java.awt.Color(255, 255, 255));
        tableSV.setRowHeight(25);
        tableSV.setSelectionBackground(new java.awt.Color(19, 90, 118));
        tableSV.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tableSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSVMouseClicked(evt);
            }
        });
        ScrollPaneSV.setViewportView(tableSV);

        addSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_table.png"))); // NOI18N
        addSV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSVMouseClicked(evt);
            }
        });

        deleteSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_table.png"))); // NOI18N
        deleteSV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteSVMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout QuanLyThongTinSVLayout = new javax.swing.GroupLayout(QuanLyThongTinSV);
        QuanLyThongTinSV.setLayout(QuanLyThongTinSVLayout);
        QuanLyThongTinSVLayout.setHorizontalGroup(
            QuanLyThongTinSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(QuanLyThongTinSVLayout.createSequentialGroup()
                .addGap(870, 870, 870)
                .addComponent(addSV, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteSV, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyThongTinSVLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(ScrollPaneSV, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        QuanLyThongTinSVLayout.setVerticalGroup(
            QuanLyThongTinSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyThongTinSVLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(QuanLyThongTinSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addSV, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(ScrollPaneSV, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 109, Short.MAX_VALUE))
        );

        add(QuanLyThongTinSV, "card2");

        UpdateSinhVien.setPreferredSize(new java.awt.Dimension(1066, 507));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(19, 90, 118));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Hệ thống quản lý ký túc xá sinh viên");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(19, 90, 118));
        jLabel24.setText("Mã phòng đăng ký :");

        txtUpEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUpEmail.setForeground(new java.awt.Color(19, 90, 118));
        txtUpEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(19, 90, 118)));
        txtUpEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpEmailActionPerformed1(evt);
            }
        });

        rdNam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdNam);
        rdNam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdNam.setForeground(new java.awt.Color(19, 90, 118));
        rdNam.setSelected(true);
        rdNam.setText("Nam");
        rdNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdNamMouseClicked(evt);
            }
        });

        rdNu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdNu);
        rdNu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdNu.setForeground(new java.awt.Color(19, 90, 118));
        rdNu.setText("Nữ");
        rdNu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdNuMouseClicked(evt);
            }
        });
        rdNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNuActionPerformed1(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(19, 90, 118));
        jLabel13.setText("Họ và tên sinh viên :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(19, 90, 118));
        jLabel14.setText("Mã số sinh viên :");

        txtUpTenSV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUpTenSV.setForeground(new java.awt.Color(19, 90, 118));
        txtUpTenSV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(19, 90, 118)));
        txtUpTenSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpTenSVActionPerformed1(evt);
            }
        });

        txtUpMaPhongSV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUpMaPhongSV.setForeground(new java.awt.Color(19, 90, 118));
        txtUpMaPhongSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUpMaPhongSVMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(19, 90, 118));
        jLabel15.setText("Căn cước công dân :");

        txtUpMaSoSV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUpMaSoSV.setForeground(new java.awt.Color(19, 90, 118));
        txtUpMaSoSV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(19, 90, 118)));
        txtUpMaSoSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpMaSoSVActionPerformed1(evt);
            }
        });

        txtUpMaLopSV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUpMaLopSV.setForeground(new java.awt.Color(19, 90, 118));
        txtUpMaLopSV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(19, 90, 118)));
        txtUpMaLopSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpMaLopSVActionPerformed1(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(19, 90, 118));
        jLabel16.setText("Ngày sinh :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(19, 90, 118));
        jLabel17.setText("Giới tính :");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(19, 90, 118));
        jLabel18.setText("Email :");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(19, 90, 118));
        jLabel19.setText("Mã lớp :");

        txtUpCCCD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUpCCCD.setForeground(new java.awt.Color(19, 90, 118));
        txtUpCCCD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(19, 90, 118)));
        txtUpCCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpCCCDActionPerformed1(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(237, 50, 55));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Duyệt thông tin sinh viên");

        btnUpdateSV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateSV.setForeground(new java.awt.Color(237, 50, 55));
        btnUpdateSV.setText("Lưu sinh viên");
        btnUpdateSV.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(237, 50, 55)));
        btnUpdateSV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateSVMouseClicked(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back_main.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(19, 90, 118));
        jLabel28.setText("Số điện thoại :");

        txtUpSoDienThoaiSV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUpSoDienThoaiSV.setForeground(new java.awt.Color(19, 90, 118));
        txtUpSoDienThoaiSV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(19, 90, 118)));
        txtUpSoDienThoaiSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpSoDienThoaiSVActionPerformed1(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(19, 90, 118));
        jLabel29.setText("Quê quán :");

        txtUpQueQuanSV.setEditable(true);
        txtUpQueQuanSV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUpQueQuanSV.setForeground(new java.awt.Color(19, 90, 118));
        txtUpQueQuanSV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "An Giang", "Bà Rịa – Vũng Tàu", "Bắc Giang", "Bắc Kạn", "Bạc Liêu", "Bắc Ninh", "Bến Tre", "Bình Định", "Bình Dương", "Bình Phước", "Bình Thuận", "Cà Mau", "Cần Thơ", "Cao Bằng", "Đà Nẵng", "Đắk Lắk", "Đắk Nông", "Điện Biên", "Đồng Nai", "Đồng Tháp", "Gia Lai", "Hà Giang", "Hà Nam", "Hà Nội", "Hà Tĩnh", "Hải Dương", "Hải Phòng", "Hậu Giang", "Hòa Bình", "Hưng Yên", "Khánh Hòa", "Kiên Giang", "Kon Tum", "Lai Châu", "Lâm Đồng", "Lạng Sơn", "Lào Cai", "Long An", "Nam Định", "Nghệ An", "Ninh Bình", "Ninh Thuận", "Phú Thọ", "Phú Yên", "Quảng Bình", "Quảng Nam", "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sóc Trăng", "Sơn La", "Tây Ninh", "Thái Bình", "Thái Nguyên", "Thanh Hóa", "Thừa Thiên Huế", "Tiền Giang", "TP Hồ Chí Minh", "Trà Vinh", "Tuyên Quang", "Vĩnh Long", "Vĩnh Phúc", "Yên Bái" }));
        txtUpQueQuanSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUpQueQuanSVMouseClicked(evt);
            }
        });
        txtUpQueQuanSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpQueQuanSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUpTenSV)
                            .addComponent(txtUpMaSoSV, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtUpNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(96, 96, 96))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(36, 36, 36)
                                    .addComponent(txtUpCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(rdNam, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdNu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(109, 109, 109)
                                        .addComponent(txtUpMaLopSV, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtUpSoDienThoaiSV, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtUpQueQuanSV, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnUpdateSV, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26)))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUpMaPhongSV, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(6, 6, 6))))
                .addGap(302, 302, 302))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtUpTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUpMaSoSV, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUpCCCD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpMaLopSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdNam)
                    .addComponent(rdNu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpSoDienThoaiSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpQueQuanSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpMaPhongSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnUpdateSV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout UpdateSinhVienLayout = new javax.swing.GroupLayout(UpdateSinhVien);
        UpdateSinhVien.setLayout(UpdateSinhVienLayout);
        UpdateSinhVienLayout.setHorizontalGroup(
            UpdateSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UpdateSinhVienLayout.setVerticalGroup(
            UpdateSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(UpdateSinhVien, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void tableSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSVMouseClicked
        // TODO add your handling code here:
        count = tableSV.getSelectedRow();
    }//GEN-LAST:event_tableSVMouseClicked

    private void ScrollPaneSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScrollPaneSVMouseClicked

    }//GEN-LAST:event_ScrollPaneSVMouseClicked

    private void ScrollPaneSVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScrollPaneSVMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ScrollPaneSVMouseExited

    private void addSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSVMouseClicked
        // TODO add your handling code here:
        if (count != -1) {
            QuanLyThongTinSV.setVisible(false);
            UpdateSinhVien.setVisible(true);
            LayThongTinSinhVienUp(count);
            AddComboBoxnew();
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên");
        }
        maphongg = txtUpMaPhongSV.getItemAt(0);
    }//GEN-LAST:event_addSVMouseClicked

    private void deleteSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteSVMouseClicked
        // TODO add your handling code here:
        LayMaSinhVien(count);
        deleteSinhVien(maSV);
    }//GEN-LAST:event_deleteSVMouseClicked

    private void txtUpEmailActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpEmailActionPerformed1
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpEmailActionPerformed1

    private void rdNuActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNuActionPerformed1
        // TODO add your handling code here:
    }//GEN-LAST:event_rdNuActionPerformed1

    private void txtUpTenSVActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpTenSVActionPerformed1
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpTenSVActionPerformed1

    private void txtUpMaSoSVActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpMaSoSVActionPerformed1
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpMaSoSVActionPerformed1

    private void txtUpMaLopSVActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpMaLopSVActionPerformed1
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpMaLopSVActionPerformed1

    private void txtUpCCCDActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpCCCDActionPerformed1
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpCCCDActionPerformed1

    private void btnUpdateSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateSVMouseClicked
        // TODO add your handling code here:
        SinhVienDAO svd = new SinhVienDAO();
        PhongDAO pd = new PhongDAO();
        //  String maphong=txtUpMaPhongSV.getItemAt(0);
        // maphong =(String) txtUpMaPhongSV.getSelectedItem();
        String maphong = maphongg;
        String hotensv = txtUpTenSV.getText().trim();
        String masv = txtUpMaSoSV.getText().trim();
        String cccdsv = txtUpCCCD.getText().trim();
        Date ngaysinhsv = txtUpNgaySinh.getDate();
        String malopsv = txtUpMaLopSV.getText().trim();
        String sodienthoaisv = txtUpSoDienThoaiSV.getText().trim();
        String emailsv = txtUpEmail.getText().trim();

        // Ràng buộc điều kiện chi tiết
        String ycmasv = "[A-Z]{1}[0-9]{2}[A-Z]{4}[0-9]{3}";
        String ycsdt = "^[0]{1}[0-9]{9}";
        String yccccd = "^([0-9]{9})*([0-9]{12})*$";
        String ycmalop = "^[A-Z]{1}[0-9]{2}[A-Z]{4}[0-9]{2}";

        //Kiểm tra tài khoản, thông tin đã tồn tại hay chưa
        boolean kiemtramaso = new SinhVienDAO().UpKiemTraMaSoSV(masv, maSV);
        // boolean kiemtramasodk = new SinhVienDangKyDAO().UpKiemTraMaSoSV(masv,maSV);
        boolean kiemtracccd = new SinhVienDAO().UpKiemTraCCCDSV(cccdsv, cccd);
        //  boolean kiemtracccddk = new SinhVienDangKyDAO().UpKiemTraCCCDSV(cccdsv,cccd);
        boolean kiemtraemail = new SinhVienDAO().UpKiemTraEmailSV(emailsv, email);
        //  boolean kiemtraemaildk = new SinhVienDangKyDAO().UpKiemTraEmailSV(emailsv,email);
        boolean kiemtrasdt = new SinhVienDAO().UpKiemTraSDTSV(sodienthoaisv, sdt);
        //  boolean kiemtrasdtdk = new SinhVienDangKyDAO().UpKiemTraSDTSV(sodienthoaisv,sdt);

        if (hotensv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không để trống họ tên sinh viên. Vui lòng điền thông tin đầy đủ!");
        } else if (masv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không để trống mã số sinh viên. Vui lòng điền thông tin đầy đủ!");
        } else if (cccdsv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không để trống căn cước công dân sinh viên. Vui lòng điền thông tin đầy đủ!");
        } else if (malopsv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không để trống mã lớp sinh viên. Vui lòng điền thông tin đầy đủ!");
        } else if (sodienthoaisv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không để trống số điện thoại sinh viên. Vui lòng điền thông tin đầy đủ!");
        } else if (emailsv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không để trống email sinh viên. Vui lòng điền thông tin đầy đủ!");
        } else if (!masv.matches(ycmasv)) {
            JOptionPane.showMessageDialog(this, "Định dạng mã số sinh viên không dúng. Ví dụ : N21DCCN001");
        } else if (!cccdsv.matches(yccccd)) {
            JOptionPane.showMessageDialog(this, "Định dạng căn cước công dân không đúng. Vui lòng nhập lại!");
        } else if (!sodienthoaisv.matches(ycsdt)) {
            JOptionPane.showMessageDialog(this, "Định dạng số điện thoại không dúng. Ví dụ : 0827364857");
        } else if (!malopsv.matches(ycmalop)) {
            JOptionPane.showMessageDialog(this, "Định dạng mã lớp không dúng. Ví dụ : D21CQCN01");
        } else if (!emailsv.contains("@gmail.com")) {
            JOptionPane.showMessageDialog(this, "Định dạng gmail không đúng. Vui lòng nhập lại");
        } else if (kiemtramaso) {
            JOptionPane.showMessageDialog(this, "Mã số sinh viên đã được đăng ký!");
        } else if (kiemtracccd) {
            JOptionPane.showMessageDialog(this, "Căn cước sinh viên đã được đăng ký!");
        } else if (kiemtraemail) {
            JOptionPane.showMessageDialog(this, "Email sinh viên đã được đăng ký!");
        } else if (kiemtrasdt) {
            JOptionPane.showMessageDialog(this, "Số điện thoại sinh viên đã được đăng ký!");
        } else {

            int test = JOptionPane.showConfirmDialog(null, "Bạn chắc có muốn thêm sinh viên hay không !", "Thông báo đăng ký", JOptionPane.YES_NO_OPTION);
            if (test == JOptionPane.YES_OPTION) {

                //LayMaSinhVien(count);
                svd.updateDKthanhcong(masv);
                // AddSinhVien();

                svd.updateMaPhong(masv, loaiphong);
                pd.AddHopDong(masv, maphong, datecr);
                showTable();
            } else if (test == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(this, "Bạn đã hủy thêm thành công");
            }
        }

        QuanLyThongTinSV.setVisible(true);
        UpdateSinhVien.setVisible(false);
    }//GEN-LAST:event_btnUpdateSVMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        QuanLyThongTinSV.setVisible(true);
        UpdateSinhVien.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txtUpSoDienThoaiSVActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpSoDienThoaiSVActionPerformed1
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpSoDienThoaiSVActionPerformed1

    private void txtUpQueQuanSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpQueQuanSVActionPerformed
        // TODO add your handling code here:
        selectedQueQuan = (String) txtUpQueQuanSV.getSelectedItem();
    }//GEN-LAST:event_txtUpQueQuanSVActionPerformed

    private void txtUpQueQuanSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUpQueQuanSVMouseClicked
        // TODO add your handling code here:
        selectedQueQuan = (String) txtUpQueQuanSV.getSelectedItem();
    }//GEN-LAST:event_txtUpQueQuanSVMouseClicked

    private void txtUpMaPhongSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUpMaPhongSVMouseClicked
        // TODO add your handling code here:
        selectedMaPhong = (String) txtUpMaPhongSV.getSelectedItem();
    }//GEN-LAST:event_txtUpMaPhongSVMouseClicked

    private void rdNamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdNamMouseClicked
        // TODO add your handling code here:

        if (rdNam.isSelected()) {
            gioitinh = "Nam";
        } else {
            gioitinh = "Nu";
        }
        AddComboBoxnew();
    }//GEN-LAST:event_rdNamMouseClicked

    private void rdNuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdNuMouseClicked
        // TODO add your handling code here:

        if (rdNam.isSelected()) {
            gioitinh = "Nam";
        } else {
            gioitinh = "Nu";
        }
        AddComboBoxnew();
    }//GEN-LAST:event_rdNuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel QuanLyThongTinSV;
    private javax.swing.JScrollPane ScrollPaneSV;
    private javax.swing.JPanel UpdateSinhVien;
    private javax.swing.JLabel addSV;
    private javax.swing.JButton btnUpdateSV;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel deleteSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tableSV;
    private javax.swing.JTextField txtUpCCCD;
    private javax.swing.JTextField txtUpEmail;
    private javax.swing.JTextField txtUpMaLopSV;
    private javax.swing.JComboBox<String> txtUpMaPhongSV;
    private javax.swing.JTextField txtUpMaSoSV;
    private com.toedter.calendar.JDateChooser txtUpNgaySinh;
    private javax.swing.JComboBox<String> txtUpQueQuanSV;
    private javax.swing.JTextField txtUpSoDienThoaiSV;
    private javax.swing.JTextField txtUpTenSV;
    // End of variables declaration//GEN-END:variables

    private void showTable() {
        listsinhvien = new SinhVienDangKyDAO().getAllThongTinSinhVienDangKynew();
        Model.setRowCount(0);
        for (ThongTinSinhVienDangKy sv : listsinhvien) {
            Model.addRow(new Object[]{
                sv.getMaSV(), sv.getTenSV(), sv.getCCCD(), sv.getGioiTinh(), sv.getNgaySinh(), sv.getMaLop(), sv.getSoDienThoai(), sv.getQueQuan()
            });
        }
    }

    private void LayMaSinhVien(int count) {
        ThongTinSinhVienDangKy sv = listsinhvien.get(count);
        maSV = sv.getMaSV();
    }

    private void LayThongTinSinhVienUp(int count) {
        ThongTinSinhVienDangKy sv = listsinhvien.get(count);
        txtUpTenSV.setText(sv.getTenSV());
        txtUpMaSoSV.setText(sv.getMaSV());
        if (sv.getGioiTinh().equals("Nam")) {
            rdNam.setSelected(true);
        } else {
            rdNu.setSelected(true);
        }
        txtUpMaLopSV.setText(sv.getMaLop());
        txtUpSoDienThoaiSV.setText(sv.getSoDienThoai());
        txtUpNgaySinh.setDate(sv.getNgaySinh());
        txtUpCCCD.setText(sv.getCCCD());
        txtUpEmail.setText(sv.getEmail());
        txtUpQueQuanSV.setSelectedItem(sv.getQueQuan());
        //tendangnhap = sv.getTenDangNhap();
        gioitinh = sv.getGioiTinh();
        sdt = sv.getSoDienThoai();
        cccd = sv.getCCCD();
        email = sv.getEmail();
        maSV = sv.getMaSV();
        loaiphong = new SinhVienDangKyDAO().LayThongTinLoaiPhong(sv.getMaSV());
    }

    public void AddSinhVien() {

        Connection conn = KetNoiSQL.getConnection();
        String sql = "insert into SinhVien (maSV, tenSV, CCCD, gioiTinh, ngaySinh, email, soDienThoai, queQuan, maLop,maPhong)"
                + "values(?,?,?,?,?,?,?,?,?,?)";
        int row = 0;
        try {
            PreparedStatement ps = conn.prepareStatement(sql);

            ps.setString(1, txtUpMaSoSV.getText().trim());
            ps.setString(2, txtUpTenSV.getText().trim());
            ps.setString(3, txtUpCCCD.getText().trim());
            if (rdNam.isSelected()) {
                ps.setString(4, "Nam");
            } else {
                ps.setString(4, "Nu");
            }
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(txtUpNgaySinh.getDate());
            ps.setString(5, date);
            ps.setString(6, txtUpEmail.getText().trim());

            ps.setString(7, txtUpSoDienThoaiSV.getText().trim());
            ps.setString(8, selectedQueQuan);
            ps.setString(9, txtUpMaLopSV.getText().trim());
            ps.setString(10, selectedMaPhong);
            row = ps.executeUpdate();
            if (row > 0) {
                JOptionPane.showMessageDialog(this, "Đăng ký sinh viên thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Nhap ma chua dung");
            }
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        showTable();

    }

    public void AddHoaDon() {
        Connection conn = KetNoiSQL.getConnection();
        String sql1 = "insert into thongtinhoadonsv (maSV, maPhong, tienPhi, thanhToan) values(?,?,?,?)";
        try {
            PreparedStatement ps1 = conn.prepareStatement(sql1);

            ps1.setString(1, txtUpMaSoSV.getText().trim());
            ps1.setString(2, selectedMaPhong);
            ps1.setDouble(3, 0);
            ps1.setInt(4, 0);

            ps1.executeUpdate();
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void deleteSinhVien(String maSV) {
        Connection conn = KetNoiSQL.getConnection();
        String sql = "delete from SinhVien where maSV = ? and trangThai=0";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, maSV);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Delete thanh cong");
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Loi xoa khong thanh cony=g");
        }
        showTable();
    }

    /* void AddComboBox() {
        Connection conn = KetNoiSQL.getConnection();

        if (loaiphong == null || loaiphong.equals("")) {
            txtUpMaPhongSV.removeAllItems();
            List<ThongTinPhong> listphong = new PhongDAO().getAllThongTinPhongGioiTinh(gioitinh);

            for (ThongTinPhong phong : listphong) {
                int soluongsv = new PhongDAO().SoLuongSV(phong.getMaPhong());
                if (soluongsv < phong.getSoLuongSVPhong()) {
                    txtUpMaPhongSV.addItem(phong.getMaPhong());
                }
            }

        } else {
            txtUpMaPhongSV.removeAllItems();
            List<ThongTinPhong> listphong = new PhongDAO().getAllThongTinPhongGioiTinhLoaiPhong(gioitinh, loaiphong);

            for (ThongTinPhong phong : listphong) {
                int soluongsv = new PhongDAO().SoLuongSV(phong.getMaPhong());
                if (soluongsv < phong.getSoLuongSVPhong()) {
                    txtUpMaPhongSV.addItem(phong.getMaPhong());
                }
            }
        }

    }
     */
    void AddComboBoxnew() {

        PhongDAO pd = new PhongDAO();
        if (pd.CheckPhong(loaiphong, gioitinh) == 1) {
            txtUpMaPhongSV.removeAllItems();
            List<ThongTinPhong> listphong = new PhongDAO().getAllThongTinPhongGioiTinhLoaiPhong(gioitinh, loaiphong);
            for (ThongTinPhong phong : listphong) {
                System.out.println("Phong :" + phong.getMaPhong());
                txtUpMaPhongSV.addItem(phong.getMaPhong());

            }

        }

    }

}
